### PR TITLE
Store as document fix and documentation on how to configure session expiry.

### LINKED ISSUE #6: `session` should be stored as an object instead of a string
When testing some things for mongosh, I found that we are storing `session` as a string. It'd be better for us to store this as an object.
`
Screenshot 2020-09-14 112035

### PR DESCRIPTION
**Pull request by No9**
This patch fixes #6 and also exposes a datetime property named `created` at the root level of the session document as using the expiry property inside the session store object gives this error.
```
db.collection.createIndex( { "session" : { "expiry": 1 } }, { expireAfterSeconds: 3600 } ) 
{
	"ok" : 0,
	"errmsg" : "Values in v:2 index key pattern cannot be of type object. Only numbers > 0, numbers < 0, and strings are allowed.",
	"code" : 67,
	"codeName" : "CannotCreateIndex"
}
```

It also provides instructions on how to configure mongo to expire the session.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -94,7 +95,9 @@ impl SessionStore for MongodbSessionStore {
         let filter = doc! { "session_id": id };
         match coll.find_one(filter, None).await? {
             None => Ok(None),
-            Some(doc) => Ok(Some(serde_json::from_str(doc.get_str("session")?)?)),
+            Some(doc) => Ok(Some(
+                bson::from_bson::<Session>(doc.get("session").unwrap().clone()).unwrap(),
```
Comment (jbr) [inline src/lib.rs]: this probably should be ? instead of unwrap — if something goes wrong with the data state we wouldn't want to panic the server

File: Cargo.toml [hunk 2]
```diff
@@ -21,6 +22,7 @@ mongodb = { version = "1.1.1", default-features = false, features = ["async-std-
 async-session = "2.0.0"
 async-trait = "0.1.36"
 serde_json = "1.0.56"
+chrono = "0.4.19"
```
Comment (jbr) [inline Cargo.toml]: async-session reexports chrono, so this dependency is unnecessary

File: src/lib.rs [hunk 3]
```diff
@@ -17,6 +17,8 @@
 
 use async_session::{Result, Session, SessionStore};
 use async_trait::async_trait;
+use chrono::Utc;
```
Comment (jbr) [inline src/lib.rs]:
```suggestion
use async_session::chrono::Utc;
```

**Comment by No9** [comment]
Thanks @jbr I've removed the external chrono link as you suggested.
If I tried to apply the `?` approach it raised a result mismatch as doc.get("session") is an option.
So I have handled the option explicitly and return an new session if the bson conversion fails

**Comment by jbr** [comment]
@No9 I don't think building a new session is ever in the responsibilities of a session store. If it can't parse a session from the stored record, that should probably be an Err with some sort of synthetic error that describes the problem

**Comment by No9** [comment]
Hey @jbr 
I think return Ok(None) is the right semantics as the actual session sub document doesn't exist.
The error from parsing of the session is handled in the `bson::from_bson` line 
https://github.com/yoshuawuyts/async-mongodb-session/pull/9/files#diff-b4aea3e418ccdb71239b96952d9cddb6R103 
And that will return an error.

**Comment by No9** [comment]
Closing as this was integrated into #11
